### ISSUE TITLE
How set action on Closed App

### ISSUE THREAD

**Issue by loreberti89** [brozot/Laravel-FCM#13]
Hello, 
I would like to ask if I can set equivalent of .addAction() and .setStyle() of notification or how use app notification builder on closed app.
Because my problem is that when my app is closed does not execute code in onMessageReceived and I can't notification.setStyle or  .addAction().

thank you for share!

**Comment by brozot** [comment]
Hi,

For Firebase message notification does not support special notifications, use a data message because it call every time onMessageReceived.

```php
$dataBuilder = new PayloadDataBuilder();
$dataBuilder->addData(['a_data' => 'my_data']);
```

maybe this thread can be help you : http://stackoverflow.com/questions/38504078/firebase-expandable-notification-show-image-when-app-is-in-background.

I hope that will help you . Please give me a feedback if that solve or not your issue.

Best regards

Nicolas

**Comment by loreberti89** [comment]
Hello, thankyou for your reply!

But my problem persist.

```
public function alert($text = null, $token, $action=null)
    {
$optionBuiler = new OptionsBuilder();
        $optionBuiler->setTimeToLive(60*20);
        $notificationBuilder = new PayloadNotificationBuilder('NOTIFY');
        $notificationBuilder->setBody($text)
            ->setSound('default');

        $dataBuilder = new PayloadDataBuilder();
       
        $dataBuilder->addData(['a_data' => 'my_data']);

        $notification = $notificationBuilder->build();
        $data = $dataBuilder->build();
        $option = $optionBuiler->build();

        FCM::sendTo($token, $option, $notification, $data);
}
```
I have this function, and when the app is open pass on onMessageReceived corretly, but when I close my app the onMessageReceived is not executed.

am I doing something wrong?

**Comment by brozot** [comment]
Hello, Try to remove the notification payload of your message like bellow:

```php
public function alert($text = null, $token, $action=null)
    {
        $optionBuiler = new OptionsBuilder();
        $optionBuiler->setTimeToLive(60*20);
        $dataBuilder = new PayloadDataBuilder();

        $dataBuilder->addData(['a_data' => 'my_data']);

        $data = $dataBuilder->build();
        $option = $optionBuiler->build();

        FCM::sendTo($token, $option, null, $data);
}
```

because when notification is present on the payload, android will handle the message and show it without passing in onMessageReceived when app is in background. 

# From FCM documentation : 
Messages with both notification and data payloads

App behavior when receiving messages that include both notification and data payloads depends on whether the app is in the background or the foreground—essentially, whether or not it is active at the time of receipt.

When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
When in the foreground, your app receives a message object with both payloads available.
Here is a JSON-formatted message containing both the notification key and the data key:
```json
  {
    "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
    "notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark",
      "icon" : "myicon"
    },
    "data" : {
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
  }
```

Please could you test it and give me a feedback ?

**Comment by loreberti89** [comment]
Yes! it Work! 
thank you!
