### ISSUE TITLE
Mutliple Android Applications

### ISSUE THREAD

**Issue by ebbbang** [brozot/Laravel-FCM#42]
How am I to integrate it for two different Android Applications using the same Laravel Application.

Both Andoid Application would have different Sender IDs.

**Comment by tahirwaseer** [comment]
As I understood from your description, I think you want to have a single Laravel back-end and have two different mobile applications. But at the end are you asking that it would have different Sender IDs? or it is your requirement, if it is, do you have any particular reason to have different sender ID because multiple applications can be supported by a single web back-end using a single sender ID.

**Comment by ebbbang** [comment]
Thanks for the reply ...
After reading your reply I found out that multiple applications can be added to same Firebase account ...
So I guess there is no need for different sender IDs ...
Thanks again ...
