### ISSUE TITLE
What is the difference between tokensToDelete() and tokensWithError()?

### ISSUE THREAD

**Issue by vigneshgurusamy** [brozot/Laravel-FCM#97]
Should I need to remove tokens from database which are returned by both the methods?

**Comment by VovikeMS** [comment]
@vigneshgurusamy , there has a difference between `tokensToDelete()` and `tokensWithError()`.

Tokens, what are marked as `tokensToDelete()` need to be deleted as well, because FCM sure that they cannot be used anymore.

In case of `tokensWithError()` this token is valid and can be used in future if you fix some sort of problems. For example: `MismatchSenderId`,  `DeviceMessageRateExceeded`.

**Comment by meyyappanv** [comment]
@VovikeMS , Thanks for the clarification. I'm afraid if the document is in sync with this clarification. 

Documentation says:

> //return Array - you must remove all this tokens in your database
> $downstreamResponse->tokensToDelete();

 and 

> // return Array (key:token, value:errror) - in production you should remove from your database the tokens present in this array
> $downstreamResponse->tokensWithError();

Shouldn't this be the other way?

**Comment by VovikeMS** [comment]
@meyyappanv After my small tests, i found that some tokens was marked as `tokensWithError();` in case of tried to use this token from another Firebase client credentials. Meaning this case cannot be happens on production stage.
Most of cases told us about completely not working this token on production, so you can trust the documentation and remove it from your DB.

**Comment by meyyappanv** [comment]
@VovikeMS Ok. I would like to explain my scenario here. I got a user's token and I tried to send push notifications to that device. Unfortunately in some cases when the phone was either turned off or there was no network coverage, I got this token in tokensWithError(), I shouldn't be deleting this. Since once he gets the network connection back or switches on the phone, if I don't have this token, I will not be able to send any further notification to that device.

**Comment by VovikeMS** [comment]
@meyyappanv If your receivers has unavailable device, FCM will not mark them as `tokensWithError `, they deliver push notification when device will be online (), but no more than you specify the `ttl`.
I think, if token was marked as `tokensWithError ` they are cannot be delivered in current configuration, no matter of device state.

But in my project, i am not remove that tokens 😃
